cc_library(
    name="checker",
    hdrs=["Checker.h", "Rule.h"],
    deps=[
        "//core/includes:def_includes",
        "//core/data:dvalue",
        !!!! DVRequire needed
    ],
    visibility=[
        "//visibility:public",
    ]
)